version: "3.9"
services:
  srec-api:
    container_name: srec-api
    image: srec-api
    build:
      context: ./api
  srec-ui:
    container_name: srec-ui
    image: srec-ui
    build:
      context: ./ui
  timescaledb:
    container_name: pgres
    image: "timescale/timescaledb:latest-pg14"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "pg_data:/var/lib/postgresql/data"

volumes:
  pg_data: