version: "3.7"

services:
  timescaledb:
    container_name: pgres
    image: "timescale/timescaledb:latest-pg14"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "pg_data:/var/lib/postgresql/data"

volumes:
  pg_data:
